<c:set var="MinWidth" value='600px'/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<fmt:setLocale value="ru"/>
<fmt:setBundle basename="labels"/>

<fmt:message key="PrintDesk" var="PrintDesk"/>
<fmt:message key="Home" var="Home"/>
<fmt:message key="Search" var="Search"/>
<fmt:message key="Help" var="Help"/>
<fmt:message key="Admin" var="Admin"/>
<fmt:message key="Branches" var="Branches"/>
<fmt:message key="Branchname" var="Branchname"/>
<fmt:message key="Reset" var="Reset"/>
<fmt:message key="Empty" var="Empty"/>
<fmt:message key="Preferences" var="Preferences"/>
<fmt:message key="Logout" var="Logout"/>
<fmt:message key="Printername" var="Printername"/>
<fmt:message key="Printers" var="Printers"/>
<fmt:message key="Details" var="Details"/>
<fmt:message key="Administrators" var="Administrators"/>
<fmt:message key="Types" var="Types"/>
<fmt:message key="Printertypes" var="Printertypes"/>
<fmt:message key="System" var="System"/>
<fmt:message key="Manualpage" var="Manualpage"/>
<fmt:message key="Installscript" var="Installscript"/>
<fmt:message key="Othersettings" var="Othersettings"/>
<fmt:message key="BranchPrinters" var="BranchPrinters"/>
<fmt:message key="Online" var="Online"/>
<fmt:message key="PrinterDetails" var="PrinterDetails"/>
<fmt:message key="Location" var="Location"/>
<fmt:message key="Vendor" var="Vendor"/>
<fmt:message key="Createddate" var="Createddate"/>
<fmt:message key="Serversharename" var="Serversharename"/>
<fmt:message key="Sendprinterlinkbyemail" var="Sendprinterlinkbyemail"/>
<fmt:message key="Sendemail" var="Sendemail"/>
<fmt:message key="PrinterInstallation" var="PrinterInstallation"/>
<fmt:message key="Install" var="Install"/>
<fmt:message key="Pleasesignin" var="Pleasesignin"/>
<fmt:message key="Login" var="Login"/>
<fmt:message key="Password" var="Password"/>
<fmt:message key="Signin" var="Signin"/>
<fmt:message key="LoPii" var="LoPii"/>
<fmt:message key="Homepage" var="Homepage"/>
<fmt:message key="Createprinter" var="Createprinter"/>
<fmt:message key="Name" var="Name"/>
<fmt:message key="Branch" var="Branch"/>
<fmt:message key="Resetviewscounttoallprinters" var="Resetviewscounttoallprinters"/>
<fmt:message key="Resetviews" var="Resetviews"/>
<fmt:message key="CleanallPrinters" var="CleanallPrinters"/>
<fmt:message key="Clean" var="Clean"/>
<fmt:message key="CleanallBranches" var="CleanallBranches"/>
<fmt:message key="CleanallPrintersTypes" var="CleanallPrintersTypes"/>
<fmt:message key="Resetinstallscripttodefault" var="Resetinstallscripttodefault"/>
<fmt:message key="Add" var="Add"/>
<fmt:message key="Inputfullnameoftheadministrator" var="Inputfullnameoftheadministrator"/>
<fmt:message key="Fullname" var="Fullname"/>
<fmt:message key="Inputloginhere" var="Inputloginhere"/>
<fmt:message key="Enterpasswordhere.Makesurethatpasswordisstrong" var="Enterpasswordhere.Makesurethatpasswordisstrong"/>
<fmt:message key="Create" var="Create"/>
<fmt:message key="AdministratorIDmustbenumber" var="AdministratorIDmustbenumber"/>
<fmt:message key="YoucannotdeletemainAdministrator" var="YoucannotdeletemainAdministrator"/>
<fmt:message key="Administratordeleted" var="Administratordeleted"/>
<fmt:message key="Administratordeletionerror" var="Administratordeletionerror"/>
<fmt:message key="Administratorcreated" var="Administratorcreated"/>
<fmt:message key="Loginmustbeuniqueorsomethingwentwrong" var="Loginmustbeuniqueorsomethingwentwrong"/>
<fmt:message key="EditBranch" var="EditBranch"/>
<fmt:message key="Administratorsaveerror" var="Administratorsaveerror"/>
<fmt:message key="Administratorsaved" var="Administratorsaved"/>
<fmt:message key="NewPassword" var="NewPassword"/>
<fmt:message key="Inputnewpasswordofadministrator" var="Inputnewpasswordofadministrator"/>
<fmt:message key="Save" var="Save"/>
<fmt:message key="EditAdmin" var="EditAdmin"/>
<fmt:message key="Inputfullnameofthebranch" var="Inputfullnameofthebranch"/>
<fmt:message key="Description" var="Description"/>
<fmt:message key="Inputdescriptionofthebranch" var="Inputdescriptionofthebranch"/>
<fmt:message key="Image" var="Image"/>
<fmt:message key="BranchIDmustbenumber" var="BranchIDmustbenumber"/>
<fmt:message key="YoucannotdeleteNonetypebranch" var="YoucannotdeleteNonetypebranch"/>
<fmt:message key="Branchdeleted" var="Branchdeleted"/>
<fmt:message key="Branchdeletionerror" var="Branchdeletionerror"/>
<fmt:message key="Branchcreated" var="Branchcreated"/>
<fmt:message key="Branchcreationerror" var="Branchcreationerror"/>
<fmt:message key="Branchnotfound" var="Branchnotfound"/>
<fmt:message key="YoucannoteditNonetypebranch" var="YoucannoteditNonetypebranch"/>
<fmt:message key="Branchsaveerror" var="Branchsaveerror"/>
<fmt:message key="Branchsaved" var="Branchsaved"/>
<fmt:message key="Deleteimage" var="Deleteimage"/>
<fmt:message key="MakechangestoInstallScriptandpressSavebuttonVariableslistedbelowwillbechangedtothespecifiedvalue"
             var="MakechangestoInstallScriptandpressSavebuttonVariableslistedbelowwillbechangedtothespecifiedvalue"/>
<fmt:message key="Printerdescription" var="Printerdescription"/>
<fmt:message key="Printersharednameonserver" var="Printersharednameonserver"/>
<fmt:message key="PrinterIDinthesystem" var="PrinterIDinthesystem"/>
<fmt:message key="PrinterbranchIDinthesystem" var="PrinterbranchIDinthesystem"/>
<fmt:message key="PrinterIPaddress" var="PrinterIPaddress"/>
<fmt:message key="Printervendor" var="Printervendor"/>
<fmt:message key="Printertype" var="Printertype"/>
<fmt:message key="Printercustomfield1" var="Printercustomfield1"/>
<fmt:message key="Installscriptsaved" var="Installscriptsaved"/>
<fmt:message key="InstallscriptnotsavedError" var="InstallscriptnotsavedError"/>
<fmt:message key="Scriptextensionsaved" var="Scriptextensionsaved"/>
<fmt:message key="ScriptextensionnotsavedError" var="ScriptextensionnotsavedError"/>
<fmt:message key="Scriptextension" var="Scriptextension"/>
<fmt:message key="Script" var="Script"/>
<fmt:message key="Manualsaved" var="Manualsaved"/>
<fmt:message key="ManualnotsavedError" var="ManualnotsavedError"/>
<fmt:message key="MakechangestoManualpageandpressSavebutton" var="MakechangestoManualpageandpressSavebutton"/>
<fmt:message key="Printerviewsreseterror" var="Printerviewsreseterror"/>
<fmt:message key="Printerviewsresetsuccess" var="Printerviewsresetsuccess"/>
<fmt:message key="Printerscleanerror" var="Printerscleanerror"/>
<fmt:message key="Printerscleansuccess" var="Printerscleansuccess"/>
<fmt:message key="Branchescleanerror" var="Branchescleanerror"/>
<fmt:message key="Branchescleansuccess" var="Branchescleansuccess"/>
<fmt:message key="PrintersTypescleanerror" var="PrintersTypescleanerror"/>
<fmt:message key="PrintersTypescleansuccess" var="PrintersTypescleansuccess"/>
<fmt:message key="Installscriptreseterror" var="Installscriptreseterror"/>
<fmt:message key="Installscriptresetsuccess" var="Installscriptresetsuccess"/>
<fmt:message key="IP" var="IP"/>
<fmt:message key="PrinterIDmustbenumber" var="PrinterIDmustbenumber"/>
<fmt:message key="Printerdeleted" var="Printerdeleted"/>
<fmt:message key="Printerdeletionerror" var="Printerdeletionerror"/>
<fmt:message key="Printercreated" var="Printercreated"/>
<fmt:message key="Printercreationerror" var="Printercreationerror"/>
<fmt:message key="PrinterIDisnotnumber" var="PrinterIDisnotnumber"/>
<fmt:message key="Printernotfound" var="Printernotfound"/>
<fmt:message key="Inputfullnameoftheprinter" var="Inputfullnameoftheprinter"/>
<fmt:message key="Inputdescriptionoftheprinter" var="Inputdescriptionoftheprinter"/>
<fmt:message key="None" var="None"/>
<fmt:message key="IPaddress" var="IPaddress"/>
<fmt:message key="InputIPaddressoftheprinter" var="InputIPaddressoftheprinter"/>
<fmt:message key="InputvendoroftheprinterForexampleHPXeroxCanonandetc"
             var="InputvendoroftheprinterForexampleHPXeroxCanonandetc"/>
<fmt:message key="Serversharedname" var="Serversharedname"/>
<fmt:message key="InputserversharednameoftheprinterForexampleserver01Printer1"
             var="InputserversharednameoftheprinterForexampleserver01Printer1"/>
<fmt:message key="Inputlocationoftheprinter" var="Inputlocationoftheprinter"/>
<fmt:message key="Customfield1" var="Customfield1"/>
<fmt:message key="Inputcustomfield1valueThisparameterisnotvisibleanywhereandcouldbeusedonlyforscriptingpurposes"
             var="Inputcustomfield1valueThisparameterisnotvisibleanywhereandcouldbeusedonlyforscriptingpurposes"/>
<fmt:message key="Editprinter" var="Editprinter"/>
<fmt:message key="Edit" var="Edit"/>
<fmt:message key="Printersaveerror" var="Printersaveerror"/>
<fmt:message key="Printersaved" var="Printersaved"/>
<fmt:message key="Enterprintertypehere" var="Enterprintertypehere"/>
<fmt:message key="PrintertypeIDmustbenumber" var="PrintertypeIDmustbenumber"/>
<fmt:message key="PrinterNonetypecannotbedeleted" var="PrinterNonetypecannotbedeleted"/>
<fmt:message key="Printertypedeleted" var="Printertypedeleted"/>
<fmt:message key="Errorprintertypedelete" var="Errorprintertypedelete"/>
<fmt:message key="EmptyprinterIDPleaseenteravalidprinterid" var="EmptyprinterIDPleaseenteravalidprinterid"/>
<fmt:message key="Branchnumbermustbeentered" var="Branchnumbermustbeentered"/>
<fmt:message key="printerdownloadisstartingSavefiletoyourdesktopandthenrunittoinstallprinter"
             var="printerdownloadisstartingSavefiletoyourdesktopandthenrunittoinstallprinter"/>
<fmt:message key="Error404" var="Error404"/>
<fmt:message key="SorryRequestedpagecouldnotbefound" var="SorryRequestedpagecouldnotbefound"/>
<fmt:message key="EmptybranchIDPleaseenteravalidbranchid" var="EmptybranchIDPleaseenteravalidbranchid"/>
<fmt:message key="Installation" var="Installation"/>
<fmt:message key="CheckyourDBconnectionorusernameorpassword" var="CheckyourDBconnectionorusernameorpassword"/>
<fmt:message key="Successinstallsystem" var="Successinstallsystem"/>
<fmt:message key="InputPasswordofthedatabase" var="InputPasswordofthedatabase"/>
<fmt:message key="InputUserofthedatabase" var="InputUserofthedatabase"/>
<fmt:message key="InputIPofthedatabase" var="InputIPofthedatabase"/>
<fmt:message key="DatabaseIP" var="DatabaseIP"/>
<fmt:message key="DatabaseUser" var="DatabaseUser"/>
<fmt:message key="DatabasePassword" var="DatabasePassword"/>
<fmt:message key="Userprofilesettings" var="Userprofilesettings"/>
<fmt:message key="Passwordarenotequal" var="Passwordarenotequal"/>
<fmt:message key="Passwordchanged" var="Passwordchanged"/>
<fmt:message key="Passwordisnotchanged" var="Passwordisnotchanged"/>
<fmt:message key="Changepassword" var="Changepassword"/>
<fmt:message key="Newpassword" var="Newpassword"/>
<fmt:message key="Inputnewpassword" var="Inputnewpassword"/>
<fmt:message key="Confirmnewpassword" var="Confirmnewpassword"/>
<fmt:message key="Inputnewpasswordagain" var="Inputnewpasswordagain"/>
<fmt:message key="Change" var="Change"/>
<fmt:message key="Scriptname" var="Scriptname"/>
<fmt:message key="Createscript" var="Createscript"/>
<fmt:message key="Scriptdeleted" var="Scriptdeleted"/>
<fmt:message key="Editscript" var="Editscript"/>
